### ISSUE TITLE
Cocoapods with Swift 3 

### ISSUE THREAD

**Issue by serejahh** [JohnSundell/Unbox#119] opened 2016-09-22 12:02 UTC
Hi, John. Thanks for the awesome lib!

I'm trying to update [UnboxedAlamofire](https://github.com/serejahh/UnboxedAlamofire) to swift 3. Unfortunately, cocoapods doesn't support specifying a branch in a podspec for dependencies. So, could you push a new podspec with swift 3? I suppose it can be `2.0`

**Comment by JohnSundell** [comment] 2016-09-22 19:30
Duplicate of https://github.com/JohnSundell/Unbox/issues/118

**Closed by JohnSundell** 2016-09-22 19:30 UTC

**Comment by JohnSundell** [comment] 2016-10-04 00:02
@serejahh Unbox 2.0 has now been released 🎉

**Comment by serejahh** [comment] 2016-10-04 07:59
What a great news! Looking forward to update UnboxedAlamofire
