### ISSUE TITLE
Transforming an enum during unboxing?

### ISSUE THREAD

**Issue by adamyanalunas** [JohnSundell/Unbox#23] opened 2016-01-16 02:09 UTC
Thanks for the helpful library. I'm integrating it into my app now and almost everything is working as expected. Everything except this one case…

Imagine you receive some JSON like this:

```json
{
  "category": "cars"
}
```

And you have an enum like this:

```swift
enum CategoryType:String {
    case None, Car, Bike, Skateboard
}

extension CategoryType:UnboxableByTransform {
    typealias UnboxRawValueType = String
    
    static func transformUnboxedValue(unboxedValue: String) -> CategoryType? {
        return CategoryType(rawValue: unboxedValue)
    }
    
}

extension CategoryType:UnboxableEnum {
    static func unboxFallbackValue() -> CategoryType {
        return .None
    }
}
```

And you have a struct like this:

```swift
struct UnboxedEvent: Unboxable {
    let category:CategoryType
    
    init(unboxer: Unboxer) {
        category = unboxer.unbox("category")
    }
}
```

The problem lies with the JSON sending back a category all lowercase, which does not match the title case of the enum. So when you try to unbox things the famous “Ambiguous use of ‘unbox’’ appears.

I had wanted to do some string manipulation in `transformUnboxedValue:` but I can't change the `UnboxRawValueType` value to `CategoryType`. Even if I could it would be a moot point because then I wouldn't have a string to manipulate.

Am I missing something? This is my first round with Unbox so despite reading the documentation there could be something I've overlooked.

**Comment by JohnSundell** [comment] 2016-01-16 19:28
Hi!

The problem is that your type conforms to both `UnboxableEnum` and `UnboxableByTransform`. A type can only conform to one Unbox protocol, otherwise Swift cannot dispatch to the correct overload of `Unboxer.unbox()` (should probably add a note about this in the `README`).

You can either choose to do your own `String -> Enum` logic using `UnboxableByTranform`, or use `UnboxableEnum` and assign explicit values to your members that matches the strings you expect in your JSON, like this:

```
enum CategoryType: String {
    case None = ""
    case Car = "car"
    case Bike = "bike"
    case Skateboard = "skateboard"
}
```

**Comment by JohnSundell** [comment] 2016-01-16 20:08
Added a note to the `README`: https://github.com/JohnSundell/Unbox/commit/1271a5a34a57367e53e7826a58b757b19fe9e76f

**Comment by JohnSundell** [comment] 2016-01-17 17:26
Closing this for now, let me know if you need any additional assistance :)

**Closed by JohnSundell** 2016-01-17 17:26 UTC

**Comment by adamyanalunas** [comment] 2016-01-18 18:03
@JohnSundell Thanks for correcting me and adding clarity to the README. I'll do my own string -> enum logic using `UnboxableByTransform`. :+1:

**Comment by JohnSundell** [comment] 2016-01-18 22:17
@adamyanalunas No problems, happy to help :rocket:
